# Generated by Django 3.2.25 on 2024-08-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('descraption', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled_status', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desig_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('descraption', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled_status', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('employe_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('father_name', models.CharField(blank=True, max_length=155, null=True)),
                ('cnic_nu', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField()),
                ('marital_status', models.CharField(max_length=250)),
                ('passport_no', models.CharField(max_length=155)),
                ('is_pf_member', models.CharField(max_length=155)),
                ('is_ss_member', models.CharField(max_length=155)),
                ('dateofconfirmation', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('bankname', models.CharField(max_length=255)),
                ('accountnumber', models.IntegerField()),
                ('relation_name', models.CharField(max_length=200)),
                ('relation_phonenum', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(default='', upload_to='media/images')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Employeentitlement',
            fields=[
                ('entitlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_pay', models.CharField(max_length=255)),
                ('conveyance_all', models.CharField(max_length=255)),
                ('medical', models.CharField(max_length=255)),
                ('utilities', models.CharField(max_length=255)),
                ('cola', models.CharField(max_length=255)),
                ('gross_pay', models.CharField(max_length=255)),
                ('effective_date', models.DateField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.designation')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Employeeducation',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_title', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Employedepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiv_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.department')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Employeattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=200)),
                ('days_worked', models.PositiveIntegerField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm_app.employe')),
            ],
        ),
    ]
